### PR TITLE
Feature/weather

### PR DESCRIPTION
**Pull request by dibdas**
The Weather App project comes at the end of the Asynchronous Javascript and APIs section of the Javascript course. It is about asynchronous communication with promises or async/await and when to use them.

### CODE REVIEW

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑🛑**

Hello @dibdas 
This is great work you did👏👏. I like how you took a simple approach.
However, few changes are required 

[REQUIRED]: When I enter a new location the data doesn't change. Kindly fix that.
[REQUIRED]: To change the metrics, you should use a toggle button, not a select box, as mentioned in the project requirements.
[REQUIRED]: When the location changes, the appearance should change as mentioned in the project requirements.
[REQUIRED]: Add this script to webpack to make it is easy to run the app.
`"scripts": {
    "dev": "webpack --mode development",
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development --open" // optional
  }
`
That's it.
Make the required changes and ask for another review👌👌👌
Happy coding💻💻💻

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @dibdas :wave:

_I must commend your efforts so far in this project. Most of the required changes have been fixed :+1:_

__However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [x] Kindly push your recent changes to deployment.

**[ OPTIONAL CHANGES ]**
- [x] For one of the added scripts (`npm start`) to work, you need to add `webpack-dev-server` to the list of your `devDependencies` in your `package.json` file.


* * *
**Please make the required changes and submit another review request when you are done.**

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by dibdas** [comment]
> **Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**


I dont get this 
could you explain me 
about the comment down below
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.

**Review by oloomoses — CHANGES_REQUESTED** [review]
Hello @dibdas,
**Great job implementing some of the changes suggested by the previous reviewers. However, some mandatory requirements are yet to be implemented.** 

- [x] Kindly ensure that the app changes its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))
- [x] I get an error when I run `npm start`. Please ensure that webpack-dev-server is included in the dev-dependencies as suggested by @NtwaliHeritier 

### Optional 
- [x] Kindly add the node_modules and .vscode folders in .gitignore. Ensure that they not being loaded into the project repo.

**Kindly implement the above changes before submitting another review.**
**Feel free to reach me on slack or leave a comment while mentioning me and I will be happy to reply**

_Slack: Oloo Moses_

**Review by voscarmv — APPROVED** [review]
# Project status: Approved 💯 ✨ 😎 👍 

### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

**Pull request merged**
